# fly.toml app configuration file generated for frosty-pine-3777 on 2023-09-29T23:15:03+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "frosty-pine-3777"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
