# render.yaml

services:
  - type: web
    name: arved-system
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free

jobs:
  - name: Keep Service Awake
    schedule: '@every 10m'
    type: curl
    command: curl -s -o /dev/null https://arved-system.onrender.com/
